spring:
  datasource:
    username: serverdbadmin
    password: 12345
    url: jdbc:mysql://localhost:3307/serverdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
  h2:
    console:
      enabled: false