spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    path: /swagger
  openapi:
    info:
      title: Your Application Name
      description: Your Application Description
      version: 1.0.0
