spring:
  datasource:
    username: serverdbadmin
    password: 12345
    url: jdbc:mysql://localhost:3307/serverdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    path: /swagger
